### ISSUE TITLE
POSIX collating elements are not supported

### ISSUE THREAD

**Issue by tprodromos** [ltrzesniewski/pcre-net#11]
Please add support for POSIX collating elements. Are extremely useful for me!
This is what I get : 
: 'Invalid pattern '[[=α=]]': POSIX collating elements are not supported at offset 1'

**Comment by ltrzesniewski** [comment]
I'm sorry, but I can't do that, as the underlying PCRE2 library [does not support them](http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC10):

> PCRE2 (and Perl) also recognize the POSIX syntax [.ch.] and [=ch=] where "ch" is a "collating element", but these are not supported, and an error is given if they are encountered.

And I doubt it will ever get implemented that way, as this feature would need to rely on the current program locale (`setlocale`). For instance `[[=e=]]` would mean different things in English and French.
The locale support is [dying away](http://www.pcre.org/current/doc/html/pcre2api.html#SEC22) in favor of Unicode:

> As more and more applications change to using Unicode, the need for this locale support is expected to die away.

Here are some things you can try:

- Expand the collating elements: you could for instance write `[eéèêë]` instead of `[[=e=]]` for a French locale.
- See if there's a Unicode character property matching what you need, to use with `\p`
- You can also use [callouts](http://www.rexegg.com/pcre-callouts.html#pcre_net), like `(.(?C{e}))` for instance, and handle them in your code by handling what the capture group matched and returning `PcreCalloutResult.Pass` or `PcreCalloutResult.Fail`.

**Comment by tprodromos** [comment]
Got it. Thanks!
