### ISSUE TITLE
Subject size limit?

### ISSUE THREAD

**Issue by AnthonyLloyd** [ltrzesniewski/pcre-net#16]
Is there a size limit to the subject string? It work for test strings of normal size. For the benchmarks game I need to do regex on a 50MB string and it just seems to hang. I've looked for an option to switch but no luck. The current C# code (https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/regexredux-csharpcore-8.html) uses PCRE directly and is fine with the size. I'm looking to use PCRE.NET for F# and C#.

**Comment by ltrzesniewski** [comment]
There's no hard-coded size limit, but PCRE accepts some configurable thresholds you can change in `PcreRegexSettings` for instance. There's nothing for subject size though.

I don't know why it would hang, at least if you run your program in 64 bit mode it should be able to allocate and handle such a string. Are you 100% sure the hang does not occur in the way you construct the string? I'll try to reproduce this.

A couple notes if you intend to use PCRE.NET in the benchmarks game:

 - The existing C# entry takes shortcuts so it will almost certainly be faster than PCRE.NET, which aims to be a general-purpose library with a user-friendly API
 - The existing entry reads and works over ASCII data, while PCRE.NET currently requires a `string`, and thus you need to convert the input to UTF-16 first, which is twice the size.
 - PCRE.NET misses some optimization opportunities (I didn't really try to optimize it *too* hard)
 - @danmosemsft may be interested in what you're doing (see #12)

**Comment by AnthonyLloyd** [comment]
I use the same code with the regex framework bits replaced with PCRE.NET (which is easy thanks!) so I'm pretty sure it's all fine. I've used win-x64 & netcoreapp3.0.

I'd really like to use PCRE.NET as its cross platform and will reduce the code needed in the benchmark. It may not be as quick given what you say but I do have an ordering optimisation that the C# entry doesn't have. I think it's closer to what should do in the benchmarks.

if you want to generate a file you could use the fasta code with 5000000 as the input. You could also just use the fasta code directly.

Many thanks for taking a look.

**Comment by ltrzesniewski** [comment]
I did a quick profile, and it turns out the first pattern matching (`>.*\n|\n`) is *unbelievably* slow.

Here's a perf trace for the 1000 first matches:

![image](https://user-images.githubusercontent.com/7913492/66000599-103f6080-e4a0-11e9-8a31-60c079858ca1.png)

The tested code is straightforward:

```C#
var subject = File.ReadAllText("input5000000.txt");

var matchCount = 0;
foreach (var _ in PcreRegex.Matches(subject, @">.*\n|\n", PcreOptions.Compiled | PcreOptions.NoUtfCheck))
{
    if (++matchCount % 10 == 0)
        Console.WriteLine(matchCount);

    if (matchCount == 1000)
        return;
}
```

So here's the thing: that `PcreOptions.NoUtfCheck` disables the UTF-16 validity check *for the pattern string*, but PCRE *still* checks UTF validity on the subject string by default. If you want to disable it for the subject string, you need to change the code like that:

```C#
var regex = new PcreRegex(@">.*\n|\n", PcreOptions.Compiled | PcreOptions.NoUtfCheck);
var matchCount = 0;

foreach (var _ in regex.Matches(subject, new PcreMatchSettings { AdditionalOptions = PcreMatchOptions.NoUtfCheck }))
{
    if (++matchCount % 10 == 0)
        Console.WriteLine(matchCount);

    if (matchCount == 1000)
        return;
}
```

This is *much much faster*:

![image](https://user-images.githubusercontent.com/7913492/66001370-a0ca7080-e4a1-11e9-995c-31ce7b369417.png)

1.20% of the time is spent on finding the top 1000 matches, compared to 99.29% previously.

So PCRE.NET is being *very* stupid here, as it executes the UTF check *for every match*, and it's very painful in your case because of such a large string. Thanks for revealing this issue! 😉 

I'll patch that to make the check only on the first iteration by default.

In the meantime I encourage you to use `new PcreMatchSettings { AdditionalOptions = PcreMatchOptions.NoUtfCheck }` in your program to disable the check entirely.

**Comment by AnthonyLloyd** [comment]
O very cool, thank you for this.

**Comment by ltrzesniewski** [comment]
I published v0.10.2 which should fix this particular issue.

But you should still use `new PcreMatchSettings { AdditionalOptions = PcreMatchOptions.NoUtfCheck }` for benchmarks. 😉

**Comment by AnthonyLloyd** [comment]
Thank you!

**Comment by AnthonyLloyd** [comment]
It improved the F# in Benchmarks Game enough to beat Java which is good. Nice result. Thanks

https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/regexredux-fsharpcore-7.html

**Comment by ltrzesniewski** [comment]
Good job! 👍

**Comment by danmosemsft** [comment]
Nice. @anthonylloyd, I’m curious why it’s still car behind the c# one (that does direct pin Coke to PCRE). 

Cc @eerhardt

**Comment by ltrzesniewski** [comment]
@danmosemsft See what I wrote [above](https://github.com/ltrzesniewski/pcre-net/issues/16#issuecomment-537206865):

> - The existing C# entry takes shortcuts so it will almost certainly be faster than PCRE.NET, which aims to be a general-purpose library with a user-friendly API
> - The existing entry reads and works over ASCII data, while PCRE.NET currently requires a string, and thus you need to convert the input to UTF-16 first, which is twice the size.
> - PCRE.NET misses some optimization opportunities (I didn't really try to optimize it too hard)

That's just a guess, but it should be accurate enough. These are *large* differences. I could try to optimize some of them away, but working on others (e.g. exposing a UTF-8 API) would require quite a bit of work.

**Comment by danmosemsft** [comment]
Thanks @ltrzesniewski . My bad, I missed your text above.

**Comment by ltrzesniewski** [comment]
No problem, I didn't expect you to read the whole thread anyway 😉
