### ISSUE TITLE
Accept Span<char> inputs?

### ISSUE THREAD

**Issue by TETYYS** [ltrzesniewski/pcre-net#18]
It would be great that pcre-net would accept Span<char> as input to `Match` and other methods.

**Comment by ltrzesniewski** [comment]
Yes, that's easily doable. It would be `ReadOnlySpan<char>` instead of `Span<char>` though.

**Comment by ltrzesniewski** [comment]
I took a quick look at this and it turns out it's not so easy after all...

Currently, the `PcreMatch` class keeps a reference to the subject string in order to lazily construct the capture groups. In order to create a `PcreMatch` from a `ReadOnlySpan<char>` subject, the groups would need to be created eagerly, which would cause a large performance impact as the value strings would all need to be created for every match and capture group.

I can see two ways to deal with that:

 - Provide an API which uses `ReadOnlyMemory<char>` instead of `ReadOnlySpan<char>` and tell the user not to change the memory contents while using a `PcreMatch` over that memory.
 - Provide a second *"advanced"* API set which would expose `ref struct` types that mirror `PcreMatch`/`PcreGroup` etc.

I think the second solution is much better, and it has some potential to provide a faster API, but it's quite a bit of work...

**Comment by ltrzesniewski** [comment]
I went with the *"advanded"* API approach. It's available in v0.12.0.

Only matching is currently implemented - I'm not sure it makes a lot of sense to implement replacing and splitting on `ReadOnlySpan<char>`, since the result would always need to produce a `string` anyway.
