### ISSUE TITLE
GetGroupNames (or similar) Implementation

### ISSUE THREAD

**Issue by ashurack** [ltrzesniewski/pcre-net#24]
I feel like I might be missing something and figured I'd ask before I venture further down the rabbit hole.  Thank you in advance!

Is it possible to get a list of group names in the current release?  I'm currently using [Regex.GetGroupNames](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.getgroupnames?view=net-5.0) but ran into too many issues since it's not a PCRE implementation.  I'm dynamically loading regex so I don't know what the names will be at runtime.

**Comment by ltrzesniewski** [comment]
It looks like that's an info I forgot to expose - oops. I'll fix it in the next version.

**Comment by ashurack** [comment]
Thank you!  I thought it was just missing from PcreRegex but wasn't 100% sure.  Awesome job and thank you so much for maintaining this project!!

**Comment by ltrzesniewski** [comment]
This is now fixed in v0.15.0: there is a new `pattern.PatternInfo.GroupNames` property.
Note that the handling of invalid group names and indices changed in this version though, see the [release notes](https://github.com/ltrzesniewski/pcre-net/releases/tag/v0.15.0) for details.

Also, thank you for the kind words! 😄
