### ISSUE TITLE
Missing closing parenthesis error

### ISSUE THREAD

**Issue by namonexarap** [ltrzesniewski/pcre-net#28]
When I use the following regular expression
`(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?`

in the following C# code
```csharp
string pattern = @"(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?";
PcreRegex regex = new PcreRegex(pattern, PcreOptions.Unicode | PcreOptions.ExtendedMore | PcreOptions.Compiled );
```
I get the following error
`PCRE.PcrePatternException: Invalid pattern '(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?': missing closing parenthesis at offset 56.`

Regular expression taken from [RFC 3986 Appendix-B](https://datatracker.ietf.org/doc/html/rfc3986#appendix-B)

The same regular expression is tested on https://ideone.com/MjJVvD

**Comment by ltrzesniewski** [comment]
Since you've specified `PcreOptions.ExtendedMore`, it enables comments inside the regex pattern.

See [here](https://pcre.org/current/doc/html/pcre2pattern.html#SEC24) for a full explanation, but in short, the last `#` character (the one which is not escaped by a `[]` character class) starts a comment, which leaves the parenthesis in front of it unclosed.

See [your pattern on regex101](https://regex101.com/r/N92NKg/1), the highlighting there shows the problem more clearly:

![image](https://github.com/ltrzesniewski/pcre-net/assets/7913492/fd4da663-4e6a-4f94-b598-8f0c217ffae9)

**Comment by namonexarap** [comment]
That's right, I completely forgot that the # character must be escaped in advanced mode.

Thank you.
