### ISSUE TITLE
.net core support?

### ISSUE THREAD

**Issue by tqtd** [ltrzesniewski/pcre-net#7]
It would be great to get pcre.net on linux.

**Comment by ltrzesniewski** [comment]
Thanks for your comment, but due to the way PCRE.NET is implemented it's unfortunately not possible without a major rewrite.

Currently, the interop code is written in C++/CLI, which [is not supported on CoreCLR](https://github.com/dotnet/coreclr/issues/659#issuecomment-91341753). It's *possible* to rewrite that layer with P/Invoke instead, but it's a large amount of work.

**Comment by ltrzesniewski** [comment]
FYI I finally rewrote the library to target netstandard2.0 in v0.8.0.

There's no Linux support yet, but I may add that in the future.

**Comment by ltrzesniewski** [comment]
I added Linux support in v0.9.0.
